import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Test Report — Zenit Tracker',
  description: 'QA Test Execution Report generated by Zenit Tracker. View pass rates, defects, and detailed test results.',
  openGraph: {
    title: 'Test Report — Zenit Tracker',
    description: 'QA Test Execution Report with detailed results, charts, and bug tracking.',
    type: 'website',
  },
};

export default function ReportLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
