#!/bin/bash
# Build the OpenNext bundle
npx @opennextjs/cloudflare build

# Deploy the worker
npx wrangler deploy

# Bulk upload secrets from environment variables
echo "Uploading secrets to worker..."
cat > /tmp/worker-secrets.json << EOF
{
  "FIREBASE_PRIVATE_KEY": "$FIREBASE_PRIVATE_KEY",
  "FIREBASE_CLIENT_EMAIL": "$FIREBASE_CLIENT_EMAIL",
  "JIRA_API_TOKEN": "$JIRA_API_TOKEN",
  "CONFLUENCE_API_TOKEN": "$CONFLUENCE_API_TOKEN",
  "GOOGLE_AI_API_KEY": "$GOOGLE_AI_API_KEY",
  "GOOGLE_AI_API_KEYS": "$GOOGLE_AI_API_KEYS",
  "GROQ_API_KEYS": "$GROQ_API_KEYS",
  "NVIDIA_API_KEY": "$NVIDIA_API_KEY",
  "HF_API_TOKEN": "$HF_API_TOKEN",
  "NEXT_PUBLIC_FIREBASE_API_KEY": "$NEXT_PUBLIC_FIREBASE_API_KEY",
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN": "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID": "$NEXT_PUBLIC_FIREBASE_PROJECT_ID",
  "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET": "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
  "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID": "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
  "NEXT_PUBLIC_FIREBASE_APP_ID": "$NEXT_PUBLIC_FIREBASE_APP_ID",
  "JIRA_BASE_URL": "$JIRA_BASE_URL",
  "JIRA_EMAIL": "$JIRA_EMAIL",
  "JIRA_PROJECT_KEY": "$JIRA_PROJECT_KEY",
  "JIRA_ORG_ID": "$JIRA_ORG_ID",
  "JIRA_CLOUD_ID": "$JIRA_CLOUD_ID",
  "CONFLUENCE_BASE_URL": "$CONFLUENCE_BASE_URL",
  "CONFLUENCE_EMAIL": "$CONFLUENCE_EMAIL",
  "NVIDIA_BASE_URL": "$NVIDIA_BASE_URL",
  "NVIDIA_MODEL": "$NVIDIA_MODEL",
  "NEXTJS_ENV": "production"
}
EOF

npx wrangler secret bulk /tmp/worker-secrets.json --name zenittracker
echo "Secrets uploaded successfully!"
